staging:
  adapter: mysql2
  database: stem_egypt
  username: stem_egypt_user
  password: stem_egypt_pwd
  host: 127.0.0.1
  port: 3306
  pool: 10
  timeout: 5000
egstage:
  adapter: mysql2
  database: eg_stage
  username: eg_stage_user
  password: eg_stage_pwd
  host: 127.0.0.1
  port: 3306
  pool: 10
  timeout: 5000
enstage:
  adapter: mysql2
  database: en_stage
  username: en_stage_user
  password: en_stage_pwd
  host: 127.0.0.1
  port: 3306
  pool: 10
  timeout: 5000

