# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 'b18b1fd390b363b99fb525688a45312735303b647168686b8c33bab9962a62fc422582d9def6333ed415d04d0ba1143e79df1bedc4854e8c44d3c48ce91d5ea2'

test:
  secret_key_base: 'cda349de3d1934b9750bb0c5aaecd9e29386e26a922d86a295cde348cd2846e8c8ec3ff7e42d8e9e8608fa4dff67c49db3136bf5da918f7988826038476e4521'

# Do not keep staging and production secrets in the repository,
# instead read values from the environment.
# Be careful about env variables if more than one env is running on a server
staging:
  secret_key_base: <%= 'ENV["SECRET_KEY_BASE"]' %>
us_stage:
  secret_key_base: <%= 'ENV["US_STAGE_SECRET_KEY_BASE"]' %>
eg_stage:
  secret_key_base: <%= 'ENV["EG_STAGE_SECRET_KEY_BASE"]' %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
# Note: this assumes that only one version of this software is running on a server
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>