# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 'b18b1fd390b363b99fb525688a45312735303b647168686b8c33bab9962a62fc422582d9def6333ed415d04d0ba1143e79df1bedc4854e8c44d3c48ce91d5ea2'

  # JWT_PASSWORD
  json_api_key: 95c271488bd77e8fa4cebfa7a7134b491d3621a1747ce7b2f97a66ddeade599cb17436d7d247729bedb443641204cc0cbb726aec16dd4b9c4e70ecab0e01e84c

  sso_url: http://localhost:3000

  curriculum_url: http://localhost:3005

  my_url: http://localhost:3006

  sso_enabled: true

  app_port: 3006

test:
  secret_key_base: 'cda349de3d1934b9750bb0c5aaecd9e29386e26a922d86a295cde348cd2846e8c8ec3ff7e42d8e9e8608fa4dff67c49db3136bf5da918f7988826038476e4521'

    # JWT_PASSWORD
  json_api_key: df3f5093998fc7b22456bde5e45de3eb3bf9baf2574a2c352716173d6226d626630d1a0e59ce288c17de80bc55a1f093a27a47c6b20eec3e9f15a4a3d59d0b8f

  sso_url: http://localhost:3000

  curriculum_url: http://localhost:3005

  my_url: http://localhost:3006

  sso_enabled: true

  app_port: 3006


# Do not keep staging and production secrets in the repository,
# instead read values from the environment.
# Be careful about env variables if more than one env is running on a server
staging:
  secret_key_base: <%= 'ENV["SECRET_KEY_BASE"]' %>
usstage:
  secret_key_base: <%= 'ENV["US_STAGE_SECRET_KEY_BASE"]' %>
egstage:
  secret_key_base: <%= 'ENV["EG_STAGE_SECRET_KEY_BASE"]' %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
# Note: this assumes that only one version of this software is running on a server
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>